Alternative INSERT OR REPLACE for postgres in SQLDatabaseController
sqlite3 supports `INSERT OR REPLACE` but postgres supports a different
form of this which is `INSERT ... ON CONFLICT ... DO UPDATE`.

See https://www.postgresql.org/docs/10/sql-insert.html

```
Traceback (most recent call last):
  File "wbia/dtool/sql_control.py", line 3306, in <module>
    db = dt.SQLDatabaseController.from_uri(os.getenv('DB_URL'))
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 498, in from_uri
    self._ensure_metadata_table()
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 620, in _ensure_metadata_table
    self.add_table(**meta_table_kw)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1742, in add_table
    self.set_metadata_val(tablename + '_' + suffix, val)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1590, in set_metadata_val
    self.executeone(operation, params, verbose=False)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1457, in executeone
    result_iter = context.execute_and_generate_results(params)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 199, in execute_and_generate_results
    context.cur.execute(context.operation, params)
psycopg2.errors.SyntaxError: syntax error at or near "OR"
LINE 1: INSERT OR REPLACE INTO metadata (metadata_key, metadata_valu...
```