WIP use sqlalchemy
Notes:

- How to do `register_converter` with sqlalchemy?  `register_adapter`
  appears to be working though

- With sqlalchemy, we need to do:

  ```
  result = connection.execute('...')
  result.fetchall()
  ```

  instead of:

  ```
  cursor.execute('...')
  cursor.fetchall()
  ```

  and:

  ```
  transaction = connection.begin()
  transaction.commit()
  ```

  instead of:

  ```
  connection.commit()
  ```

- We can't do fetch when there's no results e.g. CREATE TABLE
  statements, sqlalchemy returns an error:

  ```
  sqlalchemy.exc.ResourceClosedError: This result object does not return
  rows. It has been closed automatically.
  ```

  The way to check is by doing `result.returns_rows`.